use_frameworks!
target 'Paparajote_Tests' do
  pod 'Paparajote', :path => '../'
  pod 'Quick', :git => "https://github.com/quick/quick", :commit => "e72d6dc86bea6b0200a54c86820a6407cf20ebb0"
  pod 'Nimble', '~> 5.0'
end


target 'macOS' do
  pod 'Paparajote', :path => '../'  
end
