lane :test do
  scan(workspace: "Example/Paparajote.xcworkspace", scheme: "Tests", clean: true)
end

lane :build do
  xcodebuild(workspace: "Example/Paparajote.xcworkspace", scheme: "macOS", destination: "platform=OS X,arch=x86_64", build_settings: {"ONLY_ACTIVE_ARCH" => "NO", "CODE_SIGNING_REQUIRED" => "NO", "CODE_SIGN_IDENTITY" => "" } )
end

lane :push do
  version = version_bump_podspec(path: "Paparajote.podspec")
  git_commit(path: ["./Paparajote.podspec", "./Example/Podfile.lock"], message: "Bump podspec to #{version}")
  sh("git fetch --tags")
  sh("git tag #{version}")
  gl_token = ENV["GL_TOKEN"]
  sh("git remote set-url origin 'git@gitlab.com:caramba/Paparajote.git'")
  sh("git push origin HEAD:master --tags")
  pod_push(allow_warnings: true, verbose: true)
end
