lane :test do
  scan(output_types: "html, junit", 
    workspace: "Example/Paparajote.xcworkspace", 
    scheme: "Tests", 
    verbose: true, 
    clean: true, 
    destination: "platform=macOS,arch=x86_64",
    sdk: "macosx10.12",
    xcargs: "ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=\"\"")
end

lane :push do
  version = version_bump_podspec(path: "Paparajote.podspec")
  git_commit(path: ["./Paparajote.podspec", "./Example/Podfile.lock"], message: "Bump podspec to #{version}")
  sh("git fetch --tags")
  sh("git tag #{version}")
  gl_token = ENV["GL_TOKEN"]
  sh("git remote set-url origin 'git@gitlab.com:caramba/Paparajote.git'")
  sh("git push origin HEAD:master --tags")
  pod_push(allow_warnings: true, verbose: true)
end
