COMMIT_MESSAGE = "Bump podspec to"

lane :pods do
  cocoapods(podfile: "Example/")
end

lane :tests do
  scan(workspace: "Example/Paparajote.xcworkspace", scheme: "Tests", destination: "platform=iOS Simulator,OS=9.3,name=iPhone 6", clean: true)
end

lane :build do
  xcodebuild(workspace: "Example/Paparajote.xcworkspace", scheme: "macOS", destination: "platform=OS X,arch=x86_64", build_settings: {"ONLY_ACTIVE_ARCH" => "NO", "CODE_SIGNING_REQUIRED" => "NO", "CODE_SIGN_IDENTITY" => "" } )
end

lane :travis do
  pods
  build
  tests
end

lane :push do
  ensure_git_branch
  version = version_bump_podspec(path: "Paparajote.podspec")
  git_commit(path: ["./Paparajote.podspec", "./Example/Podfile.lock"], message: "#{COMMIT_MESSAGE} #{version}")
  changelog = changelog_from_git_commits
  github_release = set_github_release(
    repository_name: "carambalabs/Paparajote",
    api_token: ENV['GITHUB_TOKEN'],
    name: version,
    tag_name: version,
    description: changelog,
    commitish: "master"
  )
  sh("git fetch --tags")
  push_to_git_remote(remote_branch: 'master', force: false, tags: true)
  pod_push(allow_warnings: true, verbose: true)
end
